### ISSUE TITLE
Exception during initial migration when enabling via occ app:enable

### ISSUE THREAD

**Issue by aszlig** [icewind1991/permissions_overwrite#1]
Here is the relevant exception from the [full build log](https://headcounter.org/hydra/log/2a7j1r4k19h6jw68ca5jjcpfiv7zs8nl-vm-test-run-nextcloud-upgrade.drv) (cleaned up a bit, eg. without full store paths):

```
An unhandled exception has been thrown:
Error: Class 'Doctrine\DBAL\Types\Types' not found in .../apps/permissions_overwrite/lib/Migration/Version001000Date20201112164405.php:20
Stack trace:
#0 .../lib/private/DB/MigrationService.php(478): OCA\PermissionsOverwrite\Migration\Version001000Date20201112164405->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#1 .../lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('001000Date20201...', false)
#2 .../lib/private/Installer.php(157): OC\DB\MigrationService->migrate()
#3 .../core/Command/App/Enable.php(122): OC\Installer->installApp('permissions_ove...', false)
#4 .../core/Command/App/Enable.php(92): OC\Core\Command\App\Enable->enableApp('permissions_ove...', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 .../3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 .../3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 .../3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 .../3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 .../lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 .../console.php(85): OC\Console\Application->run()
#11 /nix/store/ij1jx5yr1kx8cj5fvp2jm1fl49xcwfjp-nextcloud-19.0.5.2/occ(11): require_once('/nix/store/ij1j...')
```

Note also, that this is Nextcloud 19. The integration test above is about upgrading from NC 19 to NC 20 and it already failed when enabling the app on NC 19, so I don't know whether this issue also applies to NC 20.

**Comment by icewind1991** [comment]
Can you check if 0137e8b fixes this for you

**Comment by aszlig** [comment]
@icewind1991: It does - however take this with a grain of salt, since I don't run any instances of NC 19 and I also only write more exhaustive automated tests for apps I actually use (and at the moment I don't use `permissions_overwrite` - at least not **yet**, who knows :smiley:), so for `permissions_override` with the mentioned commit applied, the upgrade test works.
